#!/bin/bash

dind=false
graph_easy=false
papertrail=false

case $DOCKER_TAG in
  latest)
    dind=true
    graph_easy=true
    papertrail=true
    ;;
  minimum)
    dind=false
    graph_easy=false
    papertrail=false
    ;;
  *)
    if echo $DOCKER_TAG | grep -q d; then
      dind=true
    fi
    if echo $DOCKER_TAG | grep -q g; then
      graph_easy=true
    fi
    if echo $DOCKER_TAG | grep -q p; then
      papertrail=true
    fi
    ;;
esac

set -x
docker build \
  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg papertrail="$papertrail" \
  --build-arg graph_easy="$graph_easy" \
  `[[ "$dind" != "true" ]] && echo --build-arg BASE="alpine"` \
  -t $IMAGE_NAME .
