#!/bin/bash

graph_easy=true
papertrail=true

case $CACHE_TAG in
  latest)
    graph_easy=true
    papertrail=true
    ;;
  grapheasy)
    graph_easy=true
    papertrail=false
    ;;
  papertrail)
    graph_easy=false
    papertrail=true
    ;;
  minimum)
    graph_easy=false
    papertrail=false
    ;;
esac

docker build \
  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg papertrail="$papertrail" \
  --build-arg graph_easy="$graph_easy" \
  -t $IMAGE_NAME .
